# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rouzeta
tagline:          'Finite State-based Korean Morphological Analyzer'
description:      'Finite State-based Korean Morphological Analyzer. Made by <a href="http://sangholee.com" target="_blank">Sangho Lee</a>'
url:              http://rouzeta.com
baseurl:          http://rouzeta.com

author:
  name:           'Sangho Lee'
  url:            http://sangholee.com

paginate:         5

gems: [jekyll-paginate, jekyll-gist, pygments]
